### ISSUE TITLE
Terraform upgrade to 0.13 throwing error 

### ISSUE THREAD

**Issue by yamu890** [cloudposse/terraform-aws-iam-system-user#39]
Hello Team, 

I was upgrading my terraform code to version 0.13 and I am finding the below error when I was trying to point to the module 
 source  = "cloudposse/iam-s3-user/aws" with version = "0.12.0". 

```Error: Invalid function argument

  on .terraform/modules/elastic_log_archive_user.s3_user/outputs.tf line 29, in output "ses_smtp_password_v4":
  29:   value       = join("", aws_iam_access_key.default.*.ses_smtp_password_v4)
    |----------------
    | aws_iam_access_key.default is tuple with 1 element

Invalid value for "lists" parameter: element 0 is null; cannot concatenate
null values.```

**Comment by joe-niland** [comment]
Hi @yamu890 
Are you using https://github.com/cloudposse/terraform-aws-iam-s3-user or this module?

**Comment by yamu890** [comment]
Hello Joe, 

I am using the module https://github.com/cloudposse/terraform-aws-iam-s3-user and that's main.tf file is pointing to this module. 
https://github.com/cloudposse/terraform-aws-iam-s3-user/blob/master/main.tf

**Comment by yamu890** [comment]
Hello @joe-niland 

Can I ask if there is any workaround to fix this ?

**Comment by benh57** [comment]
I'm seeing the same issue.

**Comment by benh57** [comment]
I'm using the module like this:
```

module "codedeploy_user" {
  source    = "git::https://github.com/cloudposse/terraform-aws-iam-system-user.git?ref=0.17.0"
  namespace    = "sms"
  stage        = "${local.env}"
  name         = "xxx"
}

```

**Comment by poupas** [comment]
Hi,

We are having the same issue with Terraform 0.13.6

In our Terraform state, the `aws_iam_access_key` resource does **not** have the `ses_smtp_password_v4` attribute.

The [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_access_key) mentions that this may happen if the resource is imported:

**"_Resource attributes such as encrypted_secret, key_fingerprint, pgp_key, secret, and ses_smtp_password_v4 are not available for imported resources as this information cannot be read from the IAM API._"**

We are pretty sure that this resource was not imported. It was created with the [terraform-aws-iam-s3-user](https://github.com/cloudposse/terraform-aws-iam-s3-user) module, which in turn uses this module.

It might be a good idea to not assume that the `ses_smtp_password_v4` is always present, and change the module accordingly.

Thank you,
Joao

**Comment by SweetOps** [comment]
has been fixed by https://github.com/cloudposse/terraform-aws-iam-system-user/pull/24

**Comment by poupas** [comment]
Hi @SweetOps . I am sorry to say that the issue is still not fixed.

I am currently using:

  * [terraform-aws-iam-s3-user](https://github.com/cloudposse/terraform-aws-iam-s3-user) version `0.15.0`, which uses
  * [terraform-aws-iam-system-user](https://github.com/cloudposse/terraform-aws-iam-system-user) version `0.18.0`

The version we are using already has the change mentioned in #24.

Consider the following output:

```
Error: Invalid function argument

  on .terraform/modules/backend_s3_user.s3_user/outputs.tf line 29, in output "ses_smtp_password_v4":
  29:   value       = join("", aws_iam_access_key.default.*.ses_smtp_password_v4)
    |----------------
    | aws_iam_access_key.default is tuple with 1 element

Invalid value for "lists" parameter: element 0 is null; cannot concatenate
null values.
```

Notice that the error is about attribute **`ses_smtp_password_v4`** and not **`ses_smtp_password`**

The issue we are facing is the one I described [above](https://github.com/cloudposse/terraform-aws-iam-system-user/issues/39#issuecomment-774124298). The documentation states that **`ses_smtp_password_v4`** might not always be present, which is in fact what is happening in our particular case.

Best regards,
Joao

**Comment by Nuru** [comment]
@poupas Please upgrade to `terraform-aws-iam-s3-user` v0.15.1 and if this is still an issue, open a PR with your patch from [here](https://github.com/cloudposse/terraform-aws-iam-system-user/issues/39#issuecomment-774124298)

**Comment by poupas** [comment]
Hi @Nuru . The issue still remains.

I will open a PR shortly.
